import { useEffect, useState } from "react";
import { Search, SlidersHorizontal, Send, ShieldCheck } from "lucide-react";
import { api } from "../api";
import { PageIntro, StatCard, RiskBadge, money, Empty } from "../components/UI";

export default function Transactions(){
 const [rows,setRows]=useState<any[]>([]);const [search,setSearch]=useState("");const [risk,setRisk]=useState("All");const [loading,setLoading]=useState(false);
 const [form,setForm]=useState({customerId:"CUS-1001",amount:"85000",country:"India",paymentMethod:"UPI",rapidTransactions:"0"});
 const load=()=>{setLoading(true);api.transactions(`?search=${encodeURIComponent(search)}&risk=${risk}`).then(setRows).finally(()=>setLoading(false))};useEffect(load,[risk]);
 return <><PageIntro title="Transaction monitoring" description="Search, filter and analyze financial transactions in the monitoring pipeline." action={<button className="secondary" onClick={load}><SlidersHorizontal size={16}/> Refresh</button>}/>
 <div className="stats-grid"><StatCard label="Transactions loaded" value={rows.length}/><StatCard label="High risk" value={rows.filter(x=>x.riskLevel==="High").length}/><StatCard label="Suspicious" value={rows.filter(x=>x.status==="Suspicious").length}/><StatCard label="Safe" value={rows.filter(x=>x.status==="Safe").length}/></div>
 <div className="panel simulator"><div><div className="eyebrow">DEMO ENGINE</div><h3>Analyze a new transaction</h3><p>Send safe dummy data through the same fraud scoring engine used by the API.</p></div><div className="form-grid"><input value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} placeholder="Customer ID"/><input value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="Amount"/><select value={form.country} onChange={e=>setForm({...form,country:e.target.value})}><option>India</option><option>UAE</option><option>Singapore</option><option>USA</option></select><select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option>UPI</option><option>Card</option><option>Net Banking</option><option>Wallet</option></select><input value={form.rapidTransactions} onChange={e=>setForm({...form,rapidTransactions:e.target.value})} placeholder="Transactions in 10 min"/><button className="primary" onClick={async()=>{await api.analyze(form);load()}}><Send size={16}/> Analyze transaction</button></div></div>
 <div className="panel"><div className="toolbar"><div className="searchbar"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search transaction, customer or country..."/></div><select value={risk} onChange={e=>setRisk(e.target.value)}><option>All</option><option>Low</option><option>Medium</option><option>High</option></select></div>{loading?<div className="loading">Loading transactions...</div>:!rows.length?<Empty/>:<div className="table-wrap"><table><thead><tr><th>ID</th><th>Customer</th><th>Amount</th><th>Country</th><th>Method</th><th>Risk</th><th>Score</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.transactionId}><td className="mono">{x.transactionId}</td><td>{x.customerName}</td><td>{money(x.amount)}</td><td>{x.country}</td><td>{x.paymentMethod}</td><td><RiskBadge level={x.riskLevel}/></td><td><strong>{x.riskScore}</strong>/100</td><td>{x.status}</td></tr>)}</tbody></table></div>}</div></>
}
